# Form implementation generated from reading ui file 'MainWindow_View.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.resize(1500, 850)
        MainWindow.setMinimumSize(QtCore.QSize(1500, 850))
        MainWindow.setWindowTitle("Brain Analysis Tool")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../.designer/Resources/Logos/logo_bat.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.0)
        MainWindow.setStyleSheet("*{\n"
"\n"
"    background: transparent;\n"
"    padding:0;\n"
"    margin:0;\n"
"    color:#fff;\n"
"}\n"
"#MainWindow\n"
"{\n"
"    border-radius:10px;\n"
"}\n"
"#centralwidget{\n"
"    background-color:#1f232a;\n"
"border-radius:10px;\n"
"}\n"
"#frm_top_header{\n"
"     border-width:1px;\n"
"    border-color: #ffa726;\n"
"    border-radius:10px;\n"
"    border-style: solid;\n"
"}\n"
"#frm_bottom_footer{\n"
"     border-width:1px;\n"
"    border-color: #ffa726;\n"
"    border-radius:10px;\n"
"    border-style: solid;\n"
"}\n"
"#frm_middle_content{\n"
"     border-width:1px;\n"
"    border-color: #ffa726;\n"
"    border-radius:10px;\n"
"    border-style: solid;\n"
"}\n"
"\n"
"#frm_app_control{\n"
"    background-color:#16191d;\n"
"    border-radius:10px;\n"
"}\n"
"#frm_app_title{\n"
"    background-color:#16191d;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"#frm_app_logo{\n"
"    background-color:#16191d;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"#frm_status_message{\n"
"    background-color:#16191d;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"#frm_status_label{\n"
"    background-color:#16191d;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"\n"
"")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.wgt_top = QtWidgets.QWidget(self.centralwidget)
        self.wgt_top.setMinimumSize(QtCore.QSize(0, 0))
        self.wgt_top.setStyleSheet("#frm_app_control QPushButton{\n"
"    background-color:#4f5966;\n"
"    text-align: center;\n"
"    border:1px solid white;\n"
"    border-radius:10px;\n"
"}\n"
"#frm_app_control QPushButton:hover{\n"
"    background-color:#94a7ae;\n"
"}")
        self.wgt_top.setObjectName("wgt_top")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.wgt_top)
        self.horizontalLayout_4.setContentsMargins(12, 12, 12, 6)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frm_top_header = QtWidgets.QFrame(self.wgt_top)
        self.frm_top_header.setMinimumSize(QtCore.QSize(0, 50))
        self.frm_top_header.setStyleSheet("")
        self.frm_top_header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_top_header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_top_header.setObjectName("frm_top_header")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frm_top_header)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frm_app_logo = QtWidgets.QFrame(self.frm_top_header)
        self.frm_app_logo.setMinimumSize(QtCore.QSize(50, 0))
        self.frm_app_logo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_app_logo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_app_logo.setObjectName("frm_app_logo")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frm_app_logo)
        self.horizontalLayout_7.setContentsMargins(20, 6, 20, 6)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_logo = QtWidgets.QLabel(self.frm_app_logo)
        self.lbl_logo.setMinimumSize(QtCore.QSize(50, 40))
        self.lbl_logo.setMaximumSize(QtCore.QSize(70, 51))
        self.lbl_logo.setAutoFillBackground(False)
        self.lbl_logo.setStyleSheet("")
        self.lbl_logo.setText("")
        self.lbl_logo.setPixmap(QtGui.QPixmap("../Resources/Logos/logo_bat.png"))
        self.lbl_logo.setScaledContents(True)
        self.lbl_logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_logo.setWordWrap(False)
        self.lbl_logo.setObjectName("lbl_logo")
        self.horizontalLayout_7.addWidget(self.lbl_logo)
        self.horizontalLayout_9.addWidget(self.frm_app_logo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.frm_app_title = QtWidgets.QFrame(self.frm_top_header)
        self.frm_app_title.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_app_title.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_app_title.setObjectName("frm_app_title")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frm_app_title)
        self.verticalLayout_11.setContentsMargins(20, 6, 20, 6)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lbl_title = QtWidgets.QLabel(self.frm_app_title)
        self.lbl_title.setStyleSheet("font: 700 18pt \"Rockwell Condensed\";\n"
"color: #ffa726;")
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout_11.addWidget(self.lbl_title)
        self.horizontalLayout_9.addWidget(self.frm_app_title)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.frm_app_control = QtWidgets.QFrame(self.frm_top_header)
        self.frm_app_control.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_app_control.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_app_control.setObjectName("frm_app_control")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frm_app_control)
        self.horizontalLayout_6.setContentsMargins(20, 6, 20, 6)
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pbtn_minimise = QtWidgets.QPushButton(self.frm_app_control)
        self.pbtn_minimise.setMinimumSize(QtCore.QSize(40, 36))
        self.pbtn_minimise.setMaximumSize(QtCore.QSize(32, 32))
        self.pbtn_minimise.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Resources/Icons/yellow/minus-circle.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_minimise.setIcon(icon1)
        self.pbtn_minimise.setIconSize(QtCore.QSize(28, 28))
        self.pbtn_minimise.setObjectName("pbtn_minimise")
        self.horizontalLayout_6.addWidget(self.pbtn_minimise)
        self.pbtn_expand = QtWidgets.QPushButton(self.frm_app_control)
        self.pbtn_expand.setMinimumSize(QtCore.QSize(40, 36))
        self.pbtn_expand.setMaximumSize(QtCore.QSize(32, 32))
        self.pbtn_expand.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Resources/Icons/yellow/maximize-2.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_expand.setIcon(icon2)
        self.pbtn_expand.setIconSize(QtCore.QSize(28, 28))
        self.pbtn_expand.setObjectName("pbtn_expand")
        self.horizontalLayout_6.addWidget(self.pbtn_expand)
        self.pbtn_exit = QtWidgets.QPushButton(self.frm_app_control)
        self.pbtn_exit.setMinimumSize(QtCore.QSize(40, 36))
        self.pbtn_exit.setMaximumSize(QtCore.QSize(32, 32))
        self.pbtn_exit.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Resources/Icons/yellow/x-octagon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_exit.setIcon(icon3)
        self.pbtn_exit.setIconSize(QtCore.QSize(28, 28))
        self.pbtn_exit.setObjectName("pbtn_exit")
        self.horizontalLayout_6.addWidget(self.pbtn_exit)
        self.horizontalLayout_9.addWidget(self.frm_app_control)
        self.horizontalLayout_4.addWidget(self.frm_top_header)
        self.verticalLayout_10.addWidget(self.wgt_top)
        self.wgt_content = QtWidgets.QWidget(self.centralwidget)
        self.wgt_content.setObjectName("wgt_content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wgt_content)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wgt_left = QtWidgets.QWidget(self.wgt_content)
        self.wgt_left.setMaximumSize(QtCore.QSize(430, 16777215))
        self.wgt_left.setStyleSheet("#frm_left_content  {\n"
"    background-color:#16191d;\n"
"     border-width:1px;\n"
"    border-color: #ffa726;\n"
"    border-radius:10px;\n"
"    border-style: solid;\n"
"}  \n"
"\n"
"#frm_left_content_left_menuTools QPushButton{\n"
"    background-color:#4f5966;\n"
"    text-align: left;\n"
"    padding:5px 10px;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"    border:1px solid white;\n"
"    border-right:none;\n"
"\n"
"}\n"
"#frm_left_content_left_menuTools QPushButton:hover{\n"
"    background-color:#94a7ae;\n"
"\n"
"}\n"
"#frm_left_content_left_menuTools QPushButton:checked{\n"
"    background-color:#29303c;\n"
"}\n"
"\n"
"#wgt_left_content_right_menuContent QPushButton{\n"
"    background-color:#4f5966;\n"
"    text-align: center;\n"
"    padding:5px;\n"
"    border-radius:10px;\n"
"    border:1px solid white;\n"
"}\n"
"#wgt_left_content_right_menuContent QPushButton:hover{\n"
"    background-color:#94a7ae;\n"
"}\n"
"\n"
"#frm_leftTool_menu_content QFrame{\n"
"    background-color:#a8acb8;\n"
"}\n"
"#wgtstck_left_content_right_menuContent QFrame{\n"
"    background-color:#29303c;\n"
"    border-bottom-right-radius:10px;\n"
"}\n"
"\n"
"#frm_left_content_right_menuContent_title{\n"
"    background-color:#29303c;\n"
"    border:1px solid #16191d;\n"
"    border-top-right-radius:10px;\n"
"    border-top-left-radius:10px;\n"
"\n"
"}\n"
"\n"
"QListWidget\n"
"{\n"
"color:black;\n"
"}\n"
"QListWidget:item { \n"
"selection-background-color: #93e6d4; \n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"color:black;\n"
"}\n"
"")
        self.wgt_left.setObjectName("wgt_left")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.wgt_left)
        self.horizontalLayout_2.setContentsMargins(12, 0, 6, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frm_left_content = QtWidgets.QFrame(self.wgt_left)
        self.frm_left_content.setStyleSheet("")
        self.frm_left_content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_left_content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_left_content.setObjectName("frm_left_content")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frm_left_content)
        self.horizontalLayout_12.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frm_left_content_left_menuTools = QtWidgets.QFrame(self.frm_left_content)
        self.frm_left_content_left_menuTools.setMaximumSize(QtCore.QSize(122, 16777215))
        self.frm_left_content_left_menuTools.setObjectName("frm_left_content_left_menuTools")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frm_left_content_left_menuTools)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frm_left_menuTools = QtWidgets.QFrame(self.frm_left_content_left_menuTools)
        self.frm_left_menuTools.setObjectName("frm_left_menuTools")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frm_left_menuTools)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frm_left_menu_openClose = QtWidgets.QFrame(self.frm_left_menuTools)
        self.frm_left_menu_openClose.setMinimumSize(QtCore.QSize(0, 40))
        self.frm_left_menu_openClose.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frm_left_menu_openClose.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_left_menu_openClose.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_left_menu_openClose.setObjectName("frm_left_menu_openClose")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frm_left_menu_openClose)
        self.verticalLayout_4.setContentsMargins(0, 0, 5, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pbtn_left_menu_openClose = QtWidgets.QPushButton(self.frm_left_menu_openClose)
        self.pbtn_left_menu_openClose.setMinimumSize(QtCore.QSize(50, 36))
        self.pbtn_left_menu_openClose.setAutoFillBackground(False)
        self.pbtn_left_menu_openClose.setStyleSheet("    border-radius:10px;\n"
"    border:1px solid white\n"
"\n"
"")
        self.pbtn_left_menu_openClose.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Resources/Icons/yellow/chevrons-left.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_left_menu_openClose.setIcon(icon4)
        self.pbtn_left_menu_openClose.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_left_menu_openClose.setObjectName("pbtn_left_menu_openClose")
        self.verticalLayout_4.addWidget(self.pbtn_left_menu_openClose, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_3.addWidget(self.frm_left_menu_openClose, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.frm_left_menu_tool_1 = QtWidgets.QFrame(self.frm_left_menuTools)
        self.frm_left_menu_tool_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_left_menu_tool_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_left_menu_tool_1.setObjectName("frm_left_menu_tool_1")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frm_left_menu_tool_1)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.pbtn_frm_left_menu_tool_project = QtWidgets.QPushButton(self.frm_left_menu_tool_1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Resources/Icons/green/folder.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_frm_left_menu_tool_project.setIcon(icon5)
        self.pbtn_frm_left_menu_tool_project.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_frm_left_menu_tool_project.setCheckable(True)
        self.pbtn_frm_left_menu_tool_project.setObjectName("pbtn_frm_left_menu_tool_project")
        self.verticalLayout_19.addWidget(self.pbtn_frm_left_menu_tool_project)
        self.verticalLayout_3.addWidget(self.frm_left_menu_tool_1)
        self.frm_left_menu_tool_2 = QtWidgets.QFrame(self.frm_left_menuTools)
        self.frm_left_menu_tool_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_left_menu_tool_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_left_menu_tool_2.setObjectName("frm_left_menu_tool_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frm_left_menu_tool_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pbtn_frm_left_menu_tool_images = QtWidgets.QPushButton(self.frm_left_menu_tool_2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Resources/Icons/green/database.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_frm_left_menu_tool_images.setIcon(icon6)
        self.pbtn_frm_left_menu_tool_images.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_frm_left_menu_tool_images.setCheckable(True)
        self.pbtn_frm_left_menu_tool_images.setChecked(False)
        self.pbtn_frm_left_menu_tool_images.setObjectName("pbtn_frm_left_menu_tool_images")
        self.verticalLayout_7.addWidget(self.pbtn_frm_left_menu_tool_images)
        self.verticalLayout_3.addWidget(self.frm_left_menu_tool_2, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frm_left_menu_tool_3 = QtWidgets.QFrame(self.frm_left_menuTools)
        self.frm_left_menu_tool_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_left_menu_tool_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_left_menu_tool_3.setObjectName("frm_left_menu_tool_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frm_left_menu_tool_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pbtn_frm_left_menu_tool_preProcess = QtWidgets.QPushButton(self.frm_left_menu_tool_3)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../Resources/Icons/green/cpu.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_frm_left_menu_tool_preProcess.setIcon(icon7)
        self.pbtn_frm_left_menu_tool_preProcess.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_frm_left_menu_tool_preProcess.setCheckable(True)
        self.pbtn_frm_left_menu_tool_preProcess.setObjectName("pbtn_frm_left_menu_tool_preProcess")
        self.verticalLayout_5.addWidget(self.pbtn_frm_left_menu_tool_preProcess)
        self.pbtn_frm_left_menu_tool_segmentation = QtWidgets.QPushButton(self.frm_left_menu_tool_3)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../Resources/Icons/green/grid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_frm_left_menu_tool_segmentation.setIcon(icon8)
        self.pbtn_frm_left_menu_tool_segmentation.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_frm_left_menu_tool_segmentation.setCheckable(True)
        self.pbtn_frm_left_menu_tool_segmentation.setObjectName("pbtn_frm_left_menu_tool_segmentation")
        self.verticalLayout_5.addWidget(self.pbtn_frm_left_menu_tool_segmentation)
        self.pbtn_frm_left_menu_tool_edit = QtWidgets.QPushButton(self.frm_left_menu_tool_3)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../Resources/Icons/green/edit.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_frm_left_menu_tool_edit.setIcon(icon9)
        self.pbtn_frm_left_menu_tool_edit.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_frm_left_menu_tool_edit.setCheckable(True)
        self.pbtn_frm_left_menu_tool_edit.setObjectName("pbtn_frm_left_menu_tool_edit")
        self.verticalLayout_5.addWidget(self.pbtn_frm_left_menu_tool_edit)
        self.verticalLayout_3.addWidget(self.frm_left_menu_tool_3, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frm_left_menu_tool_4 = QtWidgets.QFrame(self.frm_left_menuTools)
        self.frm_left_menu_tool_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_left_menu_tool_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_left_menu_tool_4.setObjectName("frm_left_menu_tool_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frm_left_menu_tool_4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pbtn_frm_left_menu_tool_3d = QtWidgets.QPushButton(self.frm_left_menu_tool_4)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../Resources/Icons/green/codepen.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_frm_left_menu_tool_3d.setIcon(icon10)
        self.pbtn_frm_left_menu_tool_3d.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_frm_left_menu_tool_3d.setCheckable(True)
        self.pbtn_frm_left_menu_tool_3d.setObjectName("pbtn_frm_left_menu_tool_3d")
        self.verticalLayout_8.addWidget(self.pbtn_frm_left_menu_tool_3d)
        self.verticalLayout_3.addWidget(self.frm_left_menu_tool_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.frm_left_menu_tool_5 = QtWidgets.QFrame(self.frm_left_menuTools)
        self.frm_left_menu_tool_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_left_menu_tool_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_left_menu_tool_5.setObjectName("frm_left_menu_tool_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frm_left_menu_tool_5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pbtn_frm_left_menu_tool_analyse = QtWidgets.QPushButton(self.frm_left_menu_tool_5)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../Resources/Icons/green/eye.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_frm_left_menu_tool_analyse.setIcon(icon11)
        self.pbtn_frm_left_menu_tool_analyse.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_frm_left_menu_tool_analyse.setObjectName("pbtn_frm_left_menu_tool_analyse")
        self.verticalLayout_9.addWidget(self.pbtn_frm_left_menu_tool_analyse)
        self.pbtn_frm_left_menu_tool_report = QtWidgets.QPushButton(self.frm_left_menu_tool_5)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../Resources/Icons/green/file-text.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_frm_left_menu_tool_report.setIcon(icon12)
        self.pbtn_frm_left_menu_tool_report.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_frm_left_menu_tool_report.setCheckable(True)
        self.pbtn_frm_left_menu_tool_report.setObjectName("pbtn_frm_left_menu_tool_report")
        self.verticalLayout_9.addWidget(self.pbtn_frm_left_menu_tool_report)
        self.verticalLayout_3.addWidget(self.frm_left_menu_tool_5)
        self.frm_left_menu_tool_6 = QtWidgets.QFrame(self.frm_left_menuTools)
        self.frm_left_menu_tool_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_left_menu_tool_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_left_menu_tool_6.setObjectName("frm_left_menu_tool_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frm_left_menu_tool_6)
        self.verticalLayout_6.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pbtn_frm_left_menu_tool_settings = QtWidgets.QPushButton(self.frm_left_menu_tool_6)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../Resources/Icons/green/settings.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_frm_left_menu_tool_settings.setIcon(icon13)
        self.pbtn_frm_left_menu_tool_settings.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_frm_left_menu_tool_settings.setCheckable(True)
        self.pbtn_frm_left_menu_tool_settings.setObjectName("pbtn_frm_left_menu_tool_settings")
        self.verticalLayout_6.addWidget(self.pbtn_frm_left_menu_tool_settings)
        self.pbtn_frm_left_menu_tool_about = QtWidgets.QPushButton(self.frm_left_menu_tool_6)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../Resources/Icons/green/info.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_frm_left_menu_tool_about.setIcon(icon14)
        self.pbtn_frm_left_menu_tool_about.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_frm_left_menu_tool_about.setCheckable(True)
        self.pbtn_frm_left_menu_tool_about.setObjectName("pbtn_frm_left_menu_tool_about")
        self.verticalLayout_6.addWidget(self.pbtn_frm_left_menu_tool_about)
        self.pbtn_frm_left_menu_tool_help = QtWidgets.QPushButton(self.frm_left_menu_tool_6)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../Resources/Icons/green/help-circle.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_frm_left_menu_tool_help.setIcon(icon15)
        self.pbtn_frm_left_menu_tool_help.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_frm_left_menu_tool_help.setCheckable(True)
        self.pbtn_frm_left_menu_tool_help.setObjectName("pbtn_frm_left_menu_tool_help")
        self.verticalLayout_6.addWidget(self.pbtn_frm_left_menu_tool_help)
        self.verticalLayout_3.addWidget(self.frm_left_menu_tool_6, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout_2.addWidget(self.frm_left_menuTools, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout_12.addWidget(self.frm_left_content_left_menuTools)
        self.frm_left_content_right_menuContent = QtWidgets.QFrame(self.frm_left_content)
        self.frm_left_content_right_menuContent.setMinimumSize(QtCore.QSize(0, 0))
        self.frm_left_content_right_menuContent.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frm_left_content_right_menuContent.setStyleSheet("")
        self.frm_left_content_right_menuContent.setObjectName("frm_left_content_right_menuContent")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frm_left_content_right_menuContent)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wgt_left_content_right_menuContent_title = QtWidgets.QWidget(self.frm_left_content_right_menuContent)
        self.wgt_left_content_right_menuContent_title.setObjectName("wgt_left_content_right_menuContent_title")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.wgt_left_content_right_menuContent_title)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frm_left_content_right_menuContent_title = QtWidgets.QFrame(self.wgt_left_content_right_menuContent_title)
        self.frm_left_content_right_menuContent_title.setMinimumSize(QtCore.QSize(0, 40))
        self.frm_left_content_right_menuContent_title.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frm_left_content_right_menuContent_title.setStyleSheet("#frm_leftToolsContents_title{\n"
"    border: 1px solid white;\n"
"}")
        self.frm_left_content_right_menuContent_title.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_left_content_right_menuContent_title.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_left_content_right_menuContent_title.setLineWidth(0)
        self.frm_left_content_right_menuContent_title.setObjectName("frm_left_content_right_menuContent_title")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frm_left_content_right_menuContent_title)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frm_left_content_right_menuContent_title_content = QtWidgets.QFrame(self.frm_left_content_right_menuContent_title)
        self.frm_left_content_right_menuContent_title_content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_left_content_right_menuContent_title_content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_left_content_right_menuContent_title_content.setObjectName("frm_left_content_right_menuContent_title_content")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frm_left_content_right_menuContent_title_content)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(10)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pbtn_left_content_right_menuContent_title_menuIcon = QtWidgets.QPushButton(self.frm_left_content_right_menuContent_title_content)
        self.pbtn_left_content_right_menuContent_title_menuIcon.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("../../../../../../.designer/Resources/Icons/yellow/archive.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_left_content_right_menuContent_title_menuIcon.setIcon(icon16)
        self.pbtn_left_content_right_menuContent_title_menuIcon.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_left_content_right_menuContent_title_menuIcon.setObjectName("pbtn_left_content_right_menuContent_title_menuIcon")
        self.horizontalLayout_15.addWidget(self.pbtn_left_content_right_menuContent_title_menuIcon)
        self.lbl_left_content_right_menuContent_title_menuTitle = QtWidgets.QLabel(self.frm_left_content_right_menuContent_title_content)
        self.lbl_left_content_right_menuContent_title_menuTitle.setStyleSheet("font: 700 14pt \"Rockwell Condensed\";")
        self.lbl_left_content_right_menuContent_title_menuTitle.setObjectName("lbl_left_content_right_menuContent_title_menuTitle")
        self.horizontalLayout_15.addWidget(self.lbl_left_content_right_menuContent_title_menuTitle)
        self.horizontalLayout_3.addWidget(self.frm_left_content_right_menuContent_title_content, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_17.addWidget(self.frm_left_content_right_menuContent_title, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addWidget(self.wgt_left_content_right_menuContent_title)
        self.wgt_left_content_right_menuContent = QtWidgets.QWidget(self.frm_left_content_right_menuContent)
        self.wgt_left_content_right_menuContent.setStyleSheet("")
        self.wgt_left_content_right_menuContent.setObjectName("wgt_left_content_right_menuContent")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.wgt_left_content_right_menuContent)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frm_left_content_right_menuContent_content = QtWidgets.QFrame(self.wgt_left_content_right_menuContent)
        self.frm_left_content_right_menuContent_content.setStyleSheet("")
        self.frm_left_content_right_menuContent_content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_left_content_right_menuContent_content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_left_content_right_menuContent_content.setObjectName("frm_left_content_right_menuContent_content")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frm_left_content_right_menuContent_content)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.wgtstck_left_content_right_menuContent = QtWidgets.QStackedWidget(self.frm_left_content_right_menuContent_content)
        self.wgtstck_left_content_right_menuContent.setStyleSheet("")
        self.wgtstck_left_content_right_menuContent.setObjectName("wgtstck_left_content_right_menuContent")
        self.page_left_content_right_menuContents_project = QtWidgets.QWidget()
        self.page_left_content_right_menuContents_project.setStyleSheet("")
        self.page_left_content_right_menuContents_project.setObjectName("page_left_content_right_menuContents_project")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.page_left_content_right_menuContents_project)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frm_projectMenu_content = QtWidgets.QFrame(self.page_left_content_right_menuContents_project)
        self.frm_projectMenu_content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_projectMenu_content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_projectMenu_content.setObjectName("frm_projectMenu_content")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frm_projectMenu_content)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frm_projectMenu_projectOperations = QtWidgets.QFrame(self.frm_projectMenu_content)
        self.frm_projectMenu_projectOperations.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_projectMenu_projectOperations.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_projectMenu_projectOperations.setObjectName("frm_projectMenu_projectOperations")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frm_projectMenu_projectOperations)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.pbtn_right_menu_tool_project_openProject = QtWidgets.QPushButton(self.frm_projectMenu_projectOperations)
        self.pbtn_right_menu_tool_project_openProject.setMinimumSize(QtCore.QSize(120, 0))
        self.pbtn_right_menu_tool_project_openProject.setStyleSheet("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("../Resources/Icons/green/book-open.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_right_menu_tool_project_openProject.setIcon(icon17)
        self.pbtn_right_menu_tool_project_openProject.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_right_menu_tool_project_openProject.setObjectName("pbtn_right_menu_tool_project_openProject")
        self.verticalLayout_22.addWidget(self.pbtn_right_menu_tool_project_openProject, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.pbtn_right_menu_tool_project_createProject = QtWidgets.QPushButton(self.frm_projectMenu_projectOperations)
        self.pbtn_right_menu_tool_project_createProject.setMinimumSize(QtCore.QSize(120, 0))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("../Resources/Icons/green/folder-plus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_right_menu_tool_project_createProject.setIcon(icon18)
        self.pbtn_right_menu_tool_project_createProject.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_right_menu_tool_project_createProject.setObjectName("pbtn_right_menu_tool_project_createProject")
        self.verticalLayout_22.addWidget(self.pbtn_right_menu_tool_project_createProject, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.pbtn_right_menu_tool_project_saveProject = QtWidgets.QPushButton(self.frm_projectMenu_projectOperations)
        self.pbtn_right_menu_tool_project_saveProject.setMinimumSize(QtCore.QSize(120, 0))
        self.pbtn_right_menu_tool_project_saveProject.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("../Resources/Icons/green/save.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_right_menu_tool_project_saveProject.setIcon(icon19)
        self.pbtn_right_menu_tool_project_saveProject.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_right_menu_tool_project_saveProject.setObjectName("pbtn_right_menu_tool_project_saveProject")
        self.verticalLayout_22.addWidget(self.pbtn_right_menu_tool_project_saveProject)
        self.pbtn_right_menu_tool_project_closeProject = QtWidgets.QPushButton(self.frm_projectMenu_projectOperations)
        self.pbtn_right_menu_tool_project_closeProject.setMinimumSize(QtCore.QSize(120, 0))
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("../Resources/Icons/green/folder-minus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_right_menu_tool_project_closeProject.setIcon(icon20)
        self.pbtn_right_menu_tool_project_closeProject.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_right_menu_tool_project_closeProject.setObjectName("pbtn_right_menu_tool_project_closeProject")
        self.verticalLayout_22.addWidget(self.pbtn_right_menu_tool_project_closeProject)
        self.verticalLayout_20.addWidget(self.frm_projectMenu_projectOperations, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_21.addWidget(self.frm_projectMenu_content)
        self.wgtstck_left_content_right_menuContent.addWidget(self.page_left_content_right_menuContents_project)
        self.page_left_content_right_menuContent_images = QtWidgets.QWidget()
        self.page_left_content_right_menuContent_images.setStyleSheet("#frm_left_menuContent_images_processingImages{\n"
"border: 1px solid white;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 1px solid white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QListWidget::item:selected { \n"
"background: #ffa726;\n"
"border: 1px solid white;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"#frm_left_menuContent_images_rawImages{\n"
"border: 1px solid white;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"#lstw_left_menuContent_images_rawImages{\n"
"background-color:#C0C2CE;\n"
"}\n"
"\n"
"#ledt_left_menuContent_images_rawImages{\n"
"background-color:#C0C2CE;\n"
"}\n"
"\n"
"#lstw_left_menuContent_images_processingImages{\n"
"background-color:#93e6d4;\n"
"}\n"
"\n"
"#ledt_left_menuContent_images_processingImage{\n"
"background-color:#93e6d4;\n"
"}")
        self.page_left_content_right_menuContent_images.setObjectName("page_left_content_right_menuContent_images")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_left_content_right_menuContent_images)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frm_left_menuContent_images = QtWidgets.QFrame(self.page_left_content_right_menuContent_images)
        self.frm_left_menuContent_images.setStyleSheet("")
        self.frm_left_menuContent_images.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_left_menuContent_images.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_left_menuContent_images.setObjectName("frm_left_menuContent_images")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frm_left_menuContent_images)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pbtn_right_menu_tool_images_loadImages = QtWidgets.QPushButton(self.frm_left_menuContent_images)
        self.pbtn_right_menu_tool_images_loadImages.setMinimumSize(QtCore.QSize(120, 0))
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("../Resources/Icons/green/image.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_right_menu_tool_images_loadImages.setIcon(icon21)
        self.pbtn_right_menu_tool_images_loadImages.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_right_menu_tool_images_loadImages.setObjectName("pbtn_right_menu_tool_images_loadImages")
        self.verticalLayout_14.addWidget(self.pbtn_right_menu_tool_images_loadImages, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.frm_left_menuContent_images_rawImages = QtWidgets.QFrame(self.frm_left_menuContent_images)
        self.frm_left_menuContent_images_rawImages.setStyleSheet("")
        self.frm_left_menuContent_images_rawImages.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_left_menuContent_images_rawImages.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_left_menuContent_images_rawImages.setObjectName("frm_left_menuContent_images_rawImages")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frm_left_menuContent_images_rawImages)
        self.verticalLayout_15.setSpacing(10)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lbl_left_menuContent_images_rawImages = QtWidgets.QLabel(self.frm_left_menuContent_images_rawImages)
        self.lbl_left_menuContent_images_rawImages.setObjectName("lbl_left_menuContent_images_rawImages")
        self.verticalLayout_15.addWidget(self.lbl_left_menuContent_images_rawImages, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.ledt_left_menuContent_images_rawImages = QtWidgets.QLineEdit(self.frm_left_menuContent_images_rawImages)
        self.ledt_left_menuContent_images_rawImages.setEnabled(False)
        self.ledt_left_menuContent_images_rawImages.setMinimumSize(QtCore.QSize(0, 25))
        self.ledt_left_menuContent_images_rawImages.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ledt_left_menuContent_images_rawImages.setReadOnly(True)
        self.ledt_left_menuContent_images_rawImages.setObjectName("ledt_left_menuContent_images_rawImages")
        self.verticalLayout_15.addWidget(self.ledt_left_menuContent_images_rawImages)
        self.lstw_left_menuContent_images_rawImages = QtWidgets.QListWidget(self.frm_left_menuContent_images_rawImages)
        self.lstw_left_menuContent_images_rawImages.setEnabled(False)
        self.lstw_left_menuContent_images_rawImages.setStyleSheet("border: 1px solid white;\n"
"border-radius:10px;\n"
"")
        self.lstw_left_menuContent_images_rawImages.setObjectName("lstw_left_menuContent_images_rawImages")
        self.verticalLayout_15.addWidget(self.lstw_left_menuContent_images_rawImages)
        self.verticalLayout_14.addWidget(self.frm_left_menuContent_images_rawImages)
        self.frm_left_menuContent_images_processingImages = QtWidgets.QFrame(self.frm_left_menuContent_images)
        self.frm_left_menuContent_images_processingImages.setStyleSheet("")
        self.frm_left_menuContent_images_processingImages.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_left_menuContent_images_processingImages.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_left_menuContent_images_processingImages.setObjectName("frm_left_menuContent_images_processingImages")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frm_left_menuContent_images_processingImages)
        self.verticalLayout_16.setSpacing(10)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.lbl_left_menuContent_images_processingImages = QtWidgets.QLabel(self.frm_left_menuContent_images_processingImages)
        self.lbl_left_menuContent_images_processingImages.setObjectName("lbl_left_menuContent_images_processingImages")
        self.verticalLayout_16.addWidget(self.lbl_left_menuContent_images_processingImages, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.ledt_left_menuContent_images_processingImage = QtWidgets.QLineEdit(self.frm_left_menuContent_images_processingImages)
        self.ledt_left_menuContent_images_processingImage.setEnabled(False)
        self.ledt_left_menuContent_images_processingImage.setMinimumSize(QtCore.QSize(0, 25))
        self.ledt_left_menuContent_images_processingImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ledt_left_menuContent_images_processingImage.setReadOnly(True)
        self.ledt_left_menuContent_images_processingImage.setObjectName("ledt_left_menuContent_images_processingImage")
        self.verticalLayout_16.addWidget(self.ledt_left_menuContent_images_processingImage)
        self.lstw_left_menuContent_images_processingImages = QtWidgets.QListWidget(self.frm_left_menuContent_images_processingImages)
        self.lstw_left_menuContent_images_processingImages.setStyleSheet("border: 1px solid white;\n"
"border-radius:10px;\n"
"\n"
"")
        self.lstw_left_menuContent_images_processingImages.setObjectName("lstw_left_menuContent_images_processingImages")
        self.verticalLayout_16.addWidget(self.lstw_left_menuContent_images_processingImages)
        self.verticalLayout_14.addWidget(self.frm_left_menuContent_images_processingImages)
        self.verticalLayout_13.addWidget(self.frm_left_menuContent_images)
        self.wgtstck_left_content_right_menuContent.addWidget(self.page_left_content_right_menuContent_images)
        self.page_left_content_right_menuContent_prePocess = QtWidgets.QWidget()
        self.page_left_content_right_menuContent_prePocess.setObjectName("page_left_content_right_menuContent_prePocess")
        self.label_2 = QtWidgets.QLabel(self.page_left_content_right_menuContent_prePocess)
        self.label_2.setGeometry(QtCore.QRect(70, 220, 49, 16))
        self.label_2.setObjectName("label_2")
        self.wgtstck_left_content_right_menuContent.addWidget(self.page_left_content_right_menuContent_prePocess)
        self.page_left_content_right_menuContent_edit = QtWidgets.QWidget()
        self.page_left_content_right_menuContent_edit.setObjectName("page_left_content_right_menuContent_edit")
        self.wgtstck_left_content_right_menuContent.addWidget(self.page_left_content_right_menuContent_edit)
        self.page_left_content_right_menuContent_segmentation = QtWidgets.QWidget()
        self.page_left_content_right_menuContent_segmentation.setObjectName("page_left_content_right_menuContent_segmentation")
        self.wgtstck_left_content_right_menuContent.addWidget(self.page_left_content_right_menuContent_segmentation)
        self.horizontalLayout_13.addWidget(self.wgtstck_left_content_right_menuContent)
        self.horizontalLayout_14.addWidget(self.frm_left_content_right_menuContent_content)
        self.verticalLayout.addWidget(self.wgt_left_content_right_menuContent)
        self.horizontalLayout_12.addWidget(self.frm_left_content_right_menuContent)
        self.horizontalLayout_2.addWidget(self.frm_left_content)
        self.horizontalLayout.addWidget(self.wgt_left, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.wgt_middle = QtWidgets.QWidget(self.wgt_content)
        self.wgt_middle.setObjectName("wgt_middle")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.wgt_middle)
        self.verticalLayout_24.setContentsMargins(6, 0, 6, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frm_middle_content = QtWidgets.QFrame(self.wgt_middle)
        self.frm_middle_content.setMinimumSize(QtCore.QSize(800, 700))
        self.frm_middle_content.setStyleSheet("")
        self.frm_middle_content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_middle_content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_middle_content.setObjectName("frm_middle_content")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frm_middle_content)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.wgtstck_middle_content = QtWidgets.QStackedWidget(self.frm_middle_content)
        self.wgtstck_middle_content.setObjectName("wgtstck_middle_content")
        self.page_middle_content_processImage = QtWidgets.QWidget()
        self.page_middle_content_processImage.setStyleSheet("#wgt_middle_content_processImage_ImageView { background-color: rgb(135, 135, 135) }")
        self.page_middle_content_processImage.setObjectName("page_middle_content_processImage")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.page_middle_content_processImage)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.frm_middle_content_processImage_imageView_container = QtWidgets.QFrame(self.page_middle_content_processImage)
        self.frm_middle_content_processImage_imageView_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_middle_content_processImage_imageView_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_middle_content_processImage_imageView_container.setObjectName("frm_middle_content_processImage_imageView_container")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frm_middle_content_processImage_imageView_container)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frm_middle_content_processImage_imageView = QtWidgets.QFrame(self.frm_middle_content_processImage_imageView_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frm_middle_content_processImage_imageView.sizePolicy().hasHeightForWidth())
        self.frm_middle_content_processImage_imageView.setSizePolicy(sizePolicy)
        self.frm_middle_content_processImage_imageView.setMinimumSize(QtCore.QSize(664, 664))
        self.frm_middle_content_processImage_imageView.setStyleSheet("")
        self.frm_middle_content_processImage_imageView.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_middle_content_processImage_imageView.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_middle_content_processImage_imageView.setLineWidth(0)
        self.frm_middle_content_processImage_imageView.setObjectName("frm_middle_content_processImage_imageView")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frm_middle_content_processImage_imageView)
        self.horizontalLayout_17.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frm_middle_content_processImage_imageView_scane = QtWidgets.QFrame(self.frm_middle_content_processImage_imageView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frm_middle_content_processImage_imageView_scane.sizePolicy().hasHeightForWidth())
        self.frm_middle_content_processImage_imageView_scane.setSizePolicy(sizePolicy)
        self.frm_middle_content_processImage_imageView_scane.setMinimumSize(QtCore.QSize(800, 600))
        self.frm_middle_content_processImage_imageView_scane.setStyleSheet("\n"
"")
        self.frm_middle_content_processImage_imageView_scane.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_middle_content_processImage_imageView_scane.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_middle_content_processImage_imageView_scane.setLineWidth(0)
        self.frm_middle_content_processImage_imageView_scane.setObjectName("frm_middle_content_processImage_imageView_scane")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frm_middle_content_processImage_imageView_scane)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_17.addWidget(self.frm_middle_content_processImage_imageView_scane, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_16.addWidget(self.frm_middle_content_processImage_imageView)
        self.verticalLayout_25.addWidget(self.frm_middle_content_processImage_imageView_container)
        self.wgtstck_middle_content.addWidget(self.page_middle_content_processImage)
        self.page_middle_content_analyse = QtWidgets.QWidget()
        self.page_middle_content_analyse.setObjectName("page_middle_content_analyse")
        self.wgtstck_middle_content.addWidget(self.page_middle_content_analyse)
        self.verticalLayout_26.addWidget(self.wgtstck_middle_content)
        self.verticalLayout_24.addWidget(self.frm_middle_content)
        self.horizontalLayout.addWidget(self.wgt_middle)
        self.wgt_right = QtWidgets.QWidget(self.wgt_content)
        self.wgt_right.setMinimumSize(QtCore.QSize(0, 0))
        self.wgt_right.setStyleSheet("#frm_right_content {\n"
"    background-color:#16191d;\n"
"     border-width:1px;\n"
"    border-color: #ffa726;\n"
"    border-radius:10px;\n"
"    border-style: solid;\n"
"}\n"
"\n"
"#frm_right_content QPushButton{\n"
"    text-align: left;\n"
"    padding:5px 10px;\n"
"    border-radius:10px;\n"
"    border:1px solid white;\n"
"    background-color:#4f5966;\n"
"\n"
"}\n"
"\n"
"#frm_right_content QPushButton:hover{\n"
"    background-color:#94a7ae;\n"
"}\n"
"\n"
"#wgtstck_right_content_tools QFrame {\n"
"    background-color:#29303c;\n"
"    border-radius:10px;\n"
"}")
        self.wgt_right.setObjectName("wgt_right")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.wgt_right)
        self.verticalLayout_18.setContentsMargins(6, 0, 12, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frm_right_content = QtWidgets.QFrame(self.wgt_right)
        self.frm_right_content.setMinimumSize(QtCore.QSize(232, 0))
        self.frm_right_content.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frm_right_content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_right_content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_right_content.setObjectName("frm_right_content")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frm_right_content)
        self.verticalLayout_23.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_23.setSpacing(6)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frm_right_content_openClose = QtWidgets.QFrame(self.frm_right_content)
        self.frm_right_content_openClose.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_right_content_openClose.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_right_content_openClose.setObjectName("frm_right_content_openClose")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frm_right_content_openClose)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.pbtn_right_content_openClose = QtWidgets.QPushButton(self.frm_right_content_openClose)
        self.pbtn_right_content_openClose.setMinimumSize(QtCore.QSize(50, 36))
        self.pbtn_right_content_openClose.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("../Resources/Icons/yellow/chevrons-right.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_right_content_openClose.setIcon(icon22)
        self.pbtn_right_content_openClose.setIconSize(QtCore.QSize(24, 24))
        self.pbtn_right_content_openClose.setObjectName("pbtn_right_content_openClose")
        self.verticalLayout_27.addWidget(self.pbtn_right_content_openClose)
        self.verticalLayout_23.addWidget(self.frm_right_content_openClose, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.frm_right_content_tools = QtWidgets.QFrame(self.frm_right_content)
        self.frm_right_content_tools.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_right_content_tools.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_right_content_tools.setObjectName("frm_right_content_tools")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frm_right_content_tools)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.wgtstck_right_content_tools = QtWidgets.QStackedWidget(self.frm_right_content_tools)
        self.wgtstck_right_content_tools.setStyleSheet("")
        self.wgtstck_right_content_tools.setObjectName("wgtstck_right_content_tools")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("")
        self.page.setObjectName("page")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_30.addWidget(self.label)
        self.verticalLayout_29.addWidget(self.frame)
        self.wgtstck_right_content_tools.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.wgtstck_right_content_tools.addWidget(self.page_2)
        self.verticalLayout_28.addWidget(self.wgtstck_right_content_tools)
        self.verticalLayout_23.addWidget(self.frm_right_content_tools)
        self.verticalLayout_18.addWidget(self.frm_right_content, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout.addWidget(self.wgt_right, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_10.addWidget(self.wgt_content)
        self.wgt_bottom = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_bottom.sizePolicy().hasHeightForWidth())
        self.wgt_bottom.setSizePolicy(sizePolicy)
        self.wgt_bottom.setStyleSheet("")
        self.wgt_bottom.setObjectName("wgt_bottom")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.wgt_bottom)
        self.horizontalLayout_5.setContentsMargins(12, 6, 12, 12)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frm_bottom_footer = QtWidgets.QFrame(self.wgt_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frm_bottom_footer.sizePolicy().hasHeightForWidth())
        self.frm_bottom_footer.setSizePolicy(sizePolicy)
        self.frm_bottom_footer.setMinimumSize(QtCore.QSize(0, 50))
        self.frm_bottom_footer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_bottom_footer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_bottom_footer.setObjectName("frm_bottom_footer")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frm_bottom_footer)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frm_status_label = QtWidgets.QFrame(self.frm_bottom_footer)
        self.frm_status_label.setMinimumSize(QtCore.QSize(122, 0))
        self.frm_status_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_status_label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_status_label.setObjectName("frm_status_label")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frm_status_label)
        self.horizontalLayout_8.setContentsMargins(20, 6, 20, 6)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lbl_status = QtWidgets.QLabel(self.frm_status_label)
        self.lbl_status.setMinimumSize(QtCore.QSize(0, 50))
        self.lbl_status.setStyleSheet("font: 700 18pt \"Rockwell Condensed\";\n"
"color: rgb(255, 170, 0);")
        self.lbl_status.setObjectName("lbl_status")
        self.horizontalLayout_8.addWidget(self.lbl_status)
        self.horizontalLayout_10.addWidget(self.frm_status_label)
        self.frm_status_message = QtWidgets.QFrame(self.frm_bottom_footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frm_status_message.sizePolicy().hasHeightForWidth())
        self.frm_status_message.setSizePolicy(sizePolicy)
        self.frm_status_message.setMinimumSize(QtCore.QSize(0, 0))
        self.frm_status_message.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_status_message.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_status_message.setObjectName("frm_status_message")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frm_status_message)
        self.verticalLayout_12.setContentsMargins(20, 6, 20, 6)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lbl_status_message = QtWidgets.QLabel(self.frm_status_message)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_status_message.sizePolicy().hasHeightForWidth())
        self.lbl_status_message.setSizePolicy(sizePolicy)
        self.lbl_status_message.setStyleSheet("font: 700  12pt \"Rockwell Condensed\";\n"
"color: rgb(255, 170, 0);")
        self.lbl_status_message.setObjectName("lbl_status_message")
        self.verticalLayout_12.addWidget(self.lbl_status_message)
        self.horizontalLayout_10.addWidget(self.frm_status_message)
        self.horizontalLayout_5.addWidget(self.frm_bottom_footer)
        self.verticalLayout_10.addWidget(self.wgt_bottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.wgtstck_left_content_right_menuContent.setCurrentIndex(1)
        self.wgtstck_middle_content.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_title.setText(_translate("MainWindow", "Brain Analysis Tool"))
        self.pbtn_left_menu_openClose.setToolTip(_translate("MainWindow", "Menu"))
        self.pbtn_frm_left_menu_tool_project.setText(_translate("MainWindow", "Project"))
        self.pbtn_frm_left_menu_tool_images.setToolTip(_translate("MainWindow", "Images"))
        self.pbtn_frm_left_menu_tool_images.setText(_translate("MainWindow", "Images"))
        self.pbtn_frm_left_menu_tool_preProcess.setToolTip(_translate("MainWindow", "PreProcess"))
        self.pbtn_frm_left_menu_tool_preProcess.setText(_translate("MainWindow", "Preprocess"))
        self.pbtn_frm_left_menu_tool_segmentation.setToolTip(_translate("MainWindow", "Segmentation"))
        self.pbtn_frm_left_menu_tool_segmentation.setText(_translate("MainWindow", "Segmentation"))
        self.pbtn_frm_left_menu_tool_edit.setToolTip(_translate("MainWindow", "Edit"))
        self.pbtn_frm_left_menu_tool_edit.setText(_translate("MainWindow", "Edit"))
        self.pbtn_frm_left_menu_tool_3d.setText(_translate("MainWindow", "3D"))
        self.pbtn_frm_left_menu_tool_analyse.setText(_translate("MainWindow", "Analyse"))
        self.pbtn_frm_left_menu_tool_report.setText(_translate("MainWindow", "Report"))
        self.pbtn_frm_left_menu_tool_settings.setToolTip(_translate("MainWindow", "Settings"))
        self.pbtn_frm_left_menu_tool_settings.setText(_translate("MainWindow", "Settings"))
        self.pbtn_frm_left_menu_tool_about.setToolTip(_translate("MainWindow", "About"))
        self.pbtn_frm_left_menu_tool_about.setText(_translate("MainWindow", "About"))
        self.pbtn_frm_left_menu_tool_help.setToolTip(_translate("MainWindow", "Help"))
        self.pbtn_frm_left_menu_tool_help.setText(_translate("MainWindow", "Help"))
        self.lbl_left_content_right_menuContent_title_menuTitle.setText(_translate("MainWindow", "MENU"))
        self.pbtn_right_menu_tool_project_openProject.setText(_translate("MainWindow", "Open Project"))
        self.pbtn_right_menu_tool_project_createProject.setText(_translate("MainWindow", "Create Project"))
        self.pbtn_right_menu_tool_project_saveProject.setText(_translate("MainWindow", "Save Project"))
        self.pbtn_right_menu_tool_project_closeProject.setText(_translate("MainWindow", "Close Project"))
        self.pbtn_right_menu_tool_images_loadImages.setText(_translate("MainWindow", "Load Images"))
        self.lbl_left_menuContent_images_rawImages.setText(_translate("MainWindow", "Raw Images"))
        self.ledt_left_menuContent_images_rawImages.setText(_translate("MainWindow", "..."))
        self.lbl_left_menuContent_images_processingImages.setText(_translate("MainWindow", "Processing Images"))
        self.ledt_left_menuContent_images_processingImage.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_status.setText(_translate("MainWindow", "Status:"))
        self.lbl_status_message.setText(_translate("MainWindow", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
