# Form implementation generated from reading ui file 'ImageScreenWidget_View.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_ImageScreenWidget(object):
    def setupUi(self, ImageScreenWidget):
        ImageScreenWidget.setObjectName("ImageScreenWidget")
        ImageScreenWidget.resize(742, 633)
        ImageScreenWidget.setStyleSheet("#ImageScreenWidget{\n"
"    background-color:#16191d;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ImageScreenWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frm_image_process_content = QtWidgets.QFrame(ImageScreenWidget)
        self.frm_image_process_content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_image_process_content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_image_process_content.setObjectName("frm_image_process_content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frm_image_process_content)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.frm_image_process_content_right = QtWidgets.QFrame(self.frm_image_process_content)
        self.frm_image_process_content_right.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_image_process_content_right.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_image_process_content_right.setObjectName("frm_image_process_content_right")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frm_image_process_content_right)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.frm_image_process_content_right_top = QtWidgets.QFrame(self.frm_image_process_content_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frm_image_process_content_right_top.sizePolicy().hasHeightForWidth())
        self.frm_image_process_content_right_top.setSizePolicy(sizePolicy)
        self.frm_image_process_content_right_top.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_image_process_content_right_top.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_image_process_content_right_top.setObjectName("frm_image_process_content_right_top")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frm_image_process_content_right_top)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frm_image_process_scane = QtWidgets.QFrame(self.frm_image_process_content_right_top)
        self.frm_image_process_scane.setAutoFillBackground(False)
        self.frm_image_process_scane.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_image_process_scane.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_image_process_scane.setObjectName("frm_image_process_scane")
        self.vlyt_frm_image_process_scane = QtWidgets.QVBoxLayout(self.frm_image_process_scane)
        self.vlyt_frm_image_process_scane.setContentsMargins(0, 0, 0, 0)
        self.vlyt_frm_image_process_scane.setSpacing(0)
        self.vlyt_frm_image_process_scane.setObjectName("vlyt_frm_image_process_scane")
        self.verticalLayout_6.addWidget(self.frm_image_process_scane)
        self.verticalLayout.addWidget(self.frm_image_process_content_right_top)
        self.frm_image_process_content_right_bottom = QtWidgets.QFrame(self.frm_image_process_content_right)
        self.frm_image_process_content_right_bottom.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_image_process_content_right_bottom.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_image_process_content_right_bottom.setObjectName("frm_image_process_content_right_bottom")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frm_image_process_content_right_bottom)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frm_image_process_content_right_bottom_top = QtWidgets.QFrame(self.frm_image_process_content_right_bottom)
        self.frm_image_process_content_right_bottom_top.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_image_process_content_right_bottom_top.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_image_process_content_right_bottom_top.setObjectName("frm_image_process_content_right_bottom_top")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frm_image_process_content_right_bottom_top)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.hsldr_frm_image_process_image_number = QtWidgets.QSlider(self.frm_image_process_content_right_bottom_top)
        self.hsldr_frm_image_process_image_number.setEnabled(False)
        self.hsldr_frm_image_process_image_number.setStyleSheet("QSlider::handle:horizontal{\n"
"    border:1px solid white;\n"
"    background: #93e6d4;\n"
"    width: 5px;\n"
"    margin-right: -1px;\n"
"    margin-left: 0px;\n"
"    margin-top: -7px;\n"
"    margin-bottom: -7px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal{\n"
"\n"
"     \n"
"    background: #565a5e;\n"
"    height: 5px;\n"
"\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal{\n"
"background: #ffa726;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal{\n"
"background: #ffa726;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:disabled\n"
"{\n"
"    background-color: #c0c0c0;\n"
"}")
        self.hsldr_frm_image_process_image_number.setTracking(True)
        self.hsldr_frm_image_process_image_number.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.hsldr_frm_image_process_image_number.setInvertedAppearance(False)
        self.hsldr_frm_image_process_image_number.setInvertedControls(False)
        self.hsldr_frm_image_process_image_number.setTickPosition(QtWidgets.QSlider.TickPosition.TicksAbove)
        self.hsldr_frm_image_process_image_number.setObjectName("hsldr_frm_image_process_image_number")
        self.verticalLayout_4.addWidget(self.hsldr_frm_image_process_image_number, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_3.addWidget(self.frm_image_process_content_right_bottom_top, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frm_image_process_content_right_bottom_bottom = QtWidgets.QFrame(self.frm_image_process_content_right_bottom)
        self.frm_image_process_content_right_bottom_bottom.setStyleSheet("")
        self.frm_image_process_content_right_bottom_bottom.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_image_process_content_right_bottom_bottom.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_image_process_content_right_bottom_bottom.setObjectName("frm_image_process_content_right_bottom_bottom")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frm_image_process_content_right_bottom_bottom)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.spnbx_frm_image_process_image_number = QtWidgets.QSpinBox(self.frm_image_process_content_right_bottom_bottom)
        self.spnbx_frm_image_process_image_number.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.spnbx_frm_image_process_image_number.setFont(font)
        self.spnbx_frm_image_process_image_number.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.spnbx_frm_image_process_image_number.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.spnbx_frm_image_process_image_number.setAutoFillBackground(False)
        self.spnbx_frm_image_process_image_number.setStyleSheet("QSpinBox {\n"
"    border:1px solid #ffffff;\n"
"    color:black;\n"
"    background:#93e6d4;\n"
"    min-height:24px;\n"
"    max-height:24px;\n"
"    min-width:60px;\n"
"    max-width:100px;\n"
"    qproperty-alignment: AlignCenter;    \n"
"    selection-background-color:transparent;\n"
"selection-color:black;\n"
"    \n"
"}\n"
" \n"
"QSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top left;\n"
"    top:0px;\n"
"    width: 24px;\n"
"    height:24px;  \n"
"    border: 1px solid #ffffff;\n"
"    background:#16191d;\n"
"    image: url(../Resources/Icons/green/arrow-right.svg);\n"
"}\n"
" \n"
"QSpinBox::up-arrow {\n"
" \n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
" \n"
"QSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"    width: 24px;\n"
"    height:24px;  \n"
"\n"
"    border: 1px solid #ffffff;\n"
"    background:#16191d;\n"
"    image: url(../Resources/Icons/green/arrow-left.svg);\n"
"}\n"
" \n"
"QSpinBox::down-button:hover,QSpinBox::up-button:hover {\n"
"    background-color:#4d4d4d;\n"
"   }\n"
" \n"
"QSpinBox::down-arrow {    \n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QSpinBox:disabled\n"
"{\n"
"    background-color: #c0c0c0;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"\n"
"")
        self.spnbx_frm_image_process_image_number.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spnbx_frm_image_process_image_number.setReadOnly(False)
        self.spnbx_frm_image_process_image_number.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.spnbx_frm_image_process_image_number.setProperty("showGroupSeparator", False)
        self.spnbx_frm_image_process_image_number.setMaximum(0)
        self.spnbx_frm_image_process_image_number.setStepType(QtWidgets.QAbstractSpinBox.StepType.DefaultStepType)
        self.spnbx_frm_image_process_image_number.setProperty("value", 0)
        self.spnbx_frm_image_process_image_number.setObjectName("spnbx_frm_image_process_image_number")
        self.horizontalLayout_3.addWidget(self.spnbx_frm_image_process_image_number)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.frm_image_process_content_right_bottom_bottom)
        self.verticalLayout.addWidget(self.frm_image_process_content_right_bottom, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.horizontalLayout.addWidget(self.frm_image_process_content_right)
        self.frm_image_process_content_left = QtWidgets.QFrame(self.frm_image_process_content)
        self.frm_image_process_content_left.setEnabled(True)
        self.frm_image_process_content_left.setStyleSheet("")
        self.frm_image_process_content_left.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_image_process_content_left.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_image_process_content_left.setObjectName("frm_image_process_content_left")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frm_image_process_content_left)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.vsldr_frm_image_process_opacity = QtWidgets.QSlider(self.frm_image_process_content_left)
        self.vsldr_frm_image_process_opacity.setEnabled(True)
        self.vsldr_frm_image_process_opacity.setStyleSheet("QSlider::handle:vertical{\n"
"    border:1px solid white;\n"
"    background: #93e6d4;\n"
"    width: 10px;\n"
"    height: 5px;\n"
"    margin-right: -7px;\n"
"    margin-left: -7px;\n"
"    margin-top: -1px;\n"
"margin-bottom: -1px;\n"
"}\n"
"\n"
"QSlider::groove:vertical{\n"
"    border:1px solid #565a5e;\n"
"    border-color: #ffa726;\n"
"    background: #565a5e;\n"
"    width: 3px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical{\n"
"background: #ffa726;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical{\n"
"background: #ffa726;\n"
"border-radius: 5px;\n"
"}\n"
"QSlider::add-page:vertical{\n"
"background: #ffa726;\n"
"border-radius: 5px;\n"
"}\n"
"QSlider::handle:vertical:disabled\n"
"{\n"
"    background-color: #c0c0c0;\n"
"}\n"
"\n"
"")
        self.vsldr_frm_image_process_opacity.setMaximum(100)
        self.vsldr_frm_image_process_opacity.setProperty("value", 100)
        self.vsldr_frm_image_process_opacity.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.vsldr_frm_image_process_opacity.setInvertedAppearance(False)
        self.vsldr_frm_image_process_opacity.setInvertedControls(False)
        self.vsldr_frm_image_process_opacity.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.vsldr_frm_image_process_opacity.setObjectName("vsldr_frm_image_process_opacity")
        self.verticalLayout_5.addWidget(self.vsldr_frm_image_process_opacity)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.horizontalLayout.addWidget(self.frm_image_process_content_left)
        self.verticalLayout_2.addWidget(self.frm_image_process_content)

        self.retranslateUi(ImageScreenWidget)
        QtCore.QMetaObject.connectSlotsByName(ImageScreenWidget)

    def retranslateUi(self, ImageScreenWidget):
        _translate = QtCore.QCoreApplication.translate
        ImageScreenWidget.setWindowTitle(_translate("ImageScreenWidget", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImageScreenWidget = QtWidgets.QWidget()
    ui = Ui_ImageScreenWidget()
    ui.setupUi(ImageScreenWidget)
    ImageScreenWidget.show()
    sys.exit(app.exec())
